In [ ]:
import pandas as pd
pd.DataFrame({"Tes" : [56,43], "NO": [34,56]}, index = ["one", "three" ])

       Tes  NO
one     56  34
three   43  56

In [ ]:
pd.Series([1,2,3,4,5], index= [20,21,22,23,34], name ="Table")

20    1
21    2
22    3
23    4
34    5
Name: Table, dtype: int64

##Imporoting a CSV

In [17]:
data = pd.read_csv("/content/main.csv")
data

,Name,Market Cap,Alpha,Beta,5Y CAGR,D/E,EPS (Q),SCORE,Capability,b,c,d,e,f,g
0,RELIANCE,"16,45,671.87",-4.86,1,12.69,0.5,13.70,23,M,5,1,4,3,5,5
1,TCS,"14,14,726.49",-4.4,0.61,12.27,0.09,34.21,23,M,5,1,4,3,5,5
2,HDFCBANK,"12,98,771.00",-5.15,1.1,6.46,0,23.11,21,M,5,1,3,2,5,5
3,BHARTIARTL,"10,26,583.48",23.02,0.64,26.47,2.04,25.54,26,S,5,5,4,5,2,5
4,ICICIBANK,"8,82,070.18",7.85,1.27,18.21,0,18.26,26,S,4,5,3,4,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,VIPIND,"4,977.79",-21.61,1.17,-5.63,1.29,-0.88,10,HR,1,1,3,1,3,1
496,BALAMINES,"4,912.64",-29.34,2.03,30.37,0.01,10.24,18,R,1,1,1,5,5,5
497,RAJESHEXPO,"4,872.38",-50.67,0.5,-25.41,0.04,1.54,16,HR,1,1,5,1,5,3
498,SPARC,"4,687.39",-27.34,1.53,-2.99,0.49,-2.45,11,HR,1,1,2,1,5,1
499,EASEMYTRIP,"4,337.96",-13.88,1.5,-,0.03,0.08,17,R,1,1,3,5,5,2

In [18]:
data.shape

(500, 15)

In [15]:
data.head()

,Name,Market Cap,Alpha,Beta,5Y CAGR,D/E,EPS (Q),SCORE,Capability,b,c,d,e,f,g
0,RELIANCE,"16,45,671.87",-4.86,1,12.69,0.5,13.70,23,M,5,1,4,3,5,5
1,TCS,"14,14,726.49",-4.4,0.61,12.27,0.09,34.21,23,M,5,1,4,3,5,5
2,HDFCBANK,"12,98,771.00",-5.15,1.1,6.46,0,23.11,21,M,5,1,3,2,5,5
3,BHARTIARTL,"10,26,583.48",23.02,0.64,26.47,2.04,25.54,26,S,5,5,4,5,2,5
4,ICICIBANK,"8,82,070.18",7.85,1.27,18.21,0,18.26,26,S,4,5,3,4,5,5

**#LECTURE 2**

In [19]:
data.Name

0        RELIANCE
1             TCS
2        HDFCBANK
3      BHARTIARTL
4       ICICIBANK
          ...
495        VIPIND
496     BALAMINES
497    RAJESHEXPO
498         SPARC
499    EASEMYTRIP
Name: Name, Length: 500, dtype: object

In [23]:
data['Name']

0        RELIANCE
1             TCS
2        HDFCBANK
3      BHARTIARTL
4       ICICIBANK
          ...
495        VIPIND
496     BALAMINES
497    RAJESHEXPO
498         SPARC
499    EASEMYTRIP
Name: Name, Length: 500, dtype: object

In [24]:
data['Name'][0]

'RELIANCE'

In [33]:
data.iloc[10]

#Pulling out the 10th Row

Name                 LICI
Market Cap    4,96,385.82
Alpha               -7.56
Beta                    -
5Y CAGR                 -
D/E                     0
EPS (Q)              17.4
SCORE                  21
Capability              M
b                       4
c                       1
d                       1
e                       5
f                       5
g                       5
Name: 10, dtype: object

In [37]:
data.loc[10, "Name"]

'LICI'

##Returns out only the required colums

In [39]:
data.loc[:,["Name" ,"b","c"]]
#Seperating out certain colums of the data

           Name  b  c
0      RELIANCE  5  1
1           TCS  5  1
2      HDFCBANK  5  1
3    BHARTIARTL  5  5
4     ICICIBANK  4  5
..          ... .. ..
495      VIPIND  1  1
496   BALAMINES  1  1
497  RAJESHEXPO  1  1
498       SPARC  1  1
499  EASEMYTRIP  1  1

[500 rows x 3 columns]

In [41]:
data

,Name,Market Cap,Alpha,Beta,5Y CAGR,D/E,EPS (Q),SCORE,Capability,b,c,d,e,f,g
0,RELIANCE,"16,45,671.87",-4.86,1,12.69,0.5,13.70,23,M,5,1,4,3,5,5
1,TCS,"14,14,726.49",-4.4,0.61,12.27,0.09,34.21,23,M,5,1,4,3,5,5
2,HDFCBANK,"12,98,771.00",-5.15,1.1,6.46,0,23.11,21,M,5,1,3,2,5,5
3,BHARTIARTL,"10,26,583.48",23.02,0.64,26.47,2.04,25.54,26,S,5,5,4,5,2,5
4,ICICIBANK,"8,82,070.18",7.85,1.27,18.21,0,18.26,26,S,4,5,3,4,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,VIPIND,"4,977.79",-21.61,1.17,-5.63,1.29,-0.88,10,HR,1,1,3,1,3,1
496,BALAMINES,"4,912.64",-29.34,2.03,30.37,0.01,10.24,18,R,1,1,1,5,5,5
497,RAJESHEXPO,"4,872.38",-50.67,0.5,-25.41,0.04,1.54,16,HR,1,1,5,1,5,3
498,SPARC,"4,687.39",-27.34,1.53,-2.99,0.49,-2.45,11,HR,1,1,2,1,5,1
499,EASEMYTRIP,"4,337.96",-13.88,1.5,-,0.03,0.08,17,R,1,1,3,5,5,2

In [45]:
data.set_index("Name")
#Setting index as NAME

,Market Cap,Alpha,Beta,5Y CAGR,D/E,EPS (Q),SCORE,Capability,b,c,d,e,f,g
Name,,,,,,,,,,,,,,
RELIANCE,"16,45,671.87",-4.86,1,12.69,0.5,13.70,23,M,5,1,4,3,5,5
TCS,"14,14,726.49",-4.4,0.61,12.27,0.09,34.21,23,M,5,1,4,3,5,5
HDFCBANK,"12,98,771.00",-5.15,1.1,6.46,0,23.11,21,M,5,1,3,2,5,5
BHARTIARTL,"10,26,583.48",23.02,0.64,26.47,2.04,25.54,26,S,5,5,4,5,2,5
ICICIBANK,"8,82,070.18",7.85,1.27,18.21,0,18.26,26,S,4,5,3,4,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
VIPIND,"4,977.79",-21.61,1.17,-5.63,1.29,-0.88,10,HR,1,1,3,1,3,1
BALAMINES,"4,912.64",-29.34,2.03,30.37,0.01,10.24,18,R,1,1,1,5,5,5
RAJESHEXPO,"4,872.38",-50.67,0.5,-25.41,0.04,1.54,16,HR,1,1,5,1,5,3
SPARC,"4,687.39",-27.34,1.53,-2.99,0.49,-2.45,11,HR,1,1,2,1,5,1
EASEMYTRIP,"4,337.96",-13.88,1.5,-,0.03,0.08,17,R,1,1,3,5,5,2

In [59]:
two =data.Capability  == "M"
two.sum()

270

#Selecting a particular Catagory

In [72]:
count = data.loc[data.Capability == "M"]
count

#Takes out the Values whose capability is "M"
#count.Name gives out only country names

,Name,Market Cap,Alpha,Beta,5Y CAGR,D/E,EPS (Q),SCORE,Capability,b,c,d,e,f,g
0,RELIANCE,"16,45,671.87",-4.86,1,12.69,0.5,13.70,23,M,5,1,4,3,5,5
1,TCS,"14,14,726.49",-4.4,0.61,12.27,0.09,34.21,23,M,5,1,4,3,5,5
2,HDFCBANK,"12,98,771.00",-5.15,1.1,6.46,0,23.11,21,M,5,1,3,2,5,5
5,INFY,"7,63,490.30",-3.65,0.81,18.4,0.09,16.43,23,M,4,1,4,4,5,5
6,SBIN,"6,49,399.98",2.64,1.3,17.32,0,21.12,24,M,4,3,3,4,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,DBREALTY,"7,497.59",16.17,0.82,72.18,0.42,0.08,22,M,1,5,4,5,5,2
477,CHENNPETRO,"7,471.63",58.43,1.13,34.3,0.25,1.40,22,M,1,5,3,5,5,3
479,EQUITASBNK,"7,252.17",5.47,0.8,-,0,0.58,22,M,1,5,4,5,5,2
489,GPPL,"6,514.84",6.91,0.67,10.73,0.03,2.06,21,M,1,5,4,3,5,3
494,GAEL,"5,200.41",5.17,0.73,24.31,0.07,1.56,23,M,1,5,4,5,5,3

In [6]:
import pandas as pd

data =pd.read_csv("/content/main.csv", index_col = 0)

In [90]:
data.isnull().sum()
#to count no.of nulls in each column

Name          0
Market Cap    0
Alpha         0
Beta          0
5Y CAGR       0
D/E           0
EPS (Q)       0
SCORE         0
Capability    0
b             0
c             0
d             0
e             0
f             0
g             0
dtype: int64

In [7]:
data

,Market Cap,Alpha,Beta,5Y CAGR,D/E,EPS (Q),SCORE,Capability,b,c,d,e,f,g
Name,,,,,,,,,,,,,,
RELIANCE,"16,45,671.87",-4.86,1,12.69,0.5,13.70,23,M,5,1,4,3,5,5
TCS,"14,14,726.49",-4.4,0.61,12.27,0.09,34.21,23,M,5,1,4,3,5,5
HDFCBANK,"12,98,771.00",-5.15,1.1,6.46,0,23.11,21,M,5,1,3,2,5,5
BHARTIARTL,"10,26,583.48",23.02,0.64,26.47,2.04,25.54,26,S,5,5,4,5,2,5
ICICIBANK,"8,82,070.18",7.85,1.27,18.21,0,18.26,26,S,4,5,3,4,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
VIPIND,"4,977.79",-21.61,1.17,-5.63,1.29,-0.88,10,HR,1,1,3,1,3,1
BALAMINES,"4,912.64",-29.34,2.03,30.37,0.01,10.24,18,R,1,1,1,5,5,5
RAJESHEXPO,"4,872.38",-50.67,0.5,-25.41,0.04,1.54,16,HR,1,1,5,1,5,3
SPARC,"4,687.39",-27.34,1.53,-2.99,0.49,-2.45,11,HR,1,1,2,1,5,1
EASEMYTRIP,"4,337.96",-13.88,1.5,-,0.03,0.08,17,R,1,1,3,5,5,2

In [8]:
data.c.describe()
#Gives info about the column in integers

count    500.00000
mean       3.87000
std        1.67891
min        1.00000
25%        2.00000
50%        5.00000
75%        5.00000
max        5.00000
Name: c, dtype: float64

In [100]:
data.Alpha.describe()

count     500
unique    465
top         -
freq       27
Name: Alpha, dtype: object

In [101]:
data.c.mean()
#Finding the mean of the c column
#data.c.describe()

3.87

In [104]:
data.Capability.unique()
##Shows the type of unique Values

array(['M', 'S', 'R', 'HR'], dtype=object)

In [106]:
data.Capability.value_counts()
#Count of Each Section

Capability
M     270
R     113
HR     61
S      56
Name: count, dtype: int64

In [112]:
r_mean = data.c.mean()
r_mean
data.c.map(lambda p : p-r_mean)

#Finding the dIfference between the mean to the numbers in the column

Name
RELIANCE     -2.87
TCS          -2.87
HDFCBANK     -2.87
BHARTIARTL    1.13
ICICIBANK     1.13
              ...
VIPIND       -2.87
BALAMINES    -2.87
RAJESHEXPO   -2.87
SPARC        -2.87
EASEMYTRIP   -2.87
Name: c, Length: 500, dtype: float64

In [113]:
data.head()

,Market Cap,Alpha,Beta,5Y CAGR,D/E,EPS (Q),SCORE,Capability,b,c,d,e,f,g
Name,,,,,,,,,,,,,,
RELIANCE,"16,45,671.87",-4.86,1,12.69,0.5,13.70,23,M,5,1,4,3,5,5
TCS,"14,14,726.49",-4.4,0.61,12.27,0.09,34.21,23,M,5,1,4,3,5,5
HDFCBANK,"12,98,771.00",-5.15,1.1,6.46,0,23.11,21,M,5,1,3,2,5,5
BHARTIARTL,"10,26,583.48",23.02,0.64,26.47,2.04,25.54,26,S,5,5,4,5,2,5
ICICIBANK,"8,82,070.18",7.85,1.27,18.21,0,18.26,26,S,4,5,3,4,5,5

In [9]:
data.loc[:, ["Beta", "Market Cap"]]

# List out onlt required coumns

            Beta    Market Cap
Name
RELIANCE       1  16,45,671.87
TCS         0.61  14,14,726.49
HDFCBANK     1.1  12,98,771.00
BHARTIARTL  0.64  10,26,583.48
ICICIBANK   1.27   8,82,070.18
...          ...           ...
VIPIND      1.17      4,977.79
BALAMINES   2.03      4,912.64
RAJESHEXPO   0.5      4,872.38
SPARC       1.53      4,687.39
EASEMYTRIP   1.5      4,337.96

[500 rows x 2 columns]

In [3]:
data.Alpha + " AND " + data.Beta

#Adjoining the data of alpha and Beta

NameError: name 'data' is not defined

In [130]:
data.d.value_counts()

d
3    177
4    162
2     67
1     63
5     31
Name: count, dtype: int64

In [11]:
data.groupby("c").c.count()

#Gives same result as of
#"data.c.value_counts()" but it gives in order

c
1    106
2     27
3     23
4     14
5    330
Name: c, dtype: int64

In [25]:
data.c.dtype

dtype('int64')

In [27]:
data

,Market Cap,Alpha,Beta,5Y CAGR,D/E,EPS (Q),SCORE,Capability,b,c,d,e,f,g
Name,,,,,,,,,,,,,,
RELIANCE,"16,45,671.87",-4.86,1,12.69,0.5,13.70,23,M,5,1,4,3,5,5
TCS,"14,14,726.49",-4.4,0.61,12.27,0.09,34.21,23,M,5,1,4,3,5,5
HDFCBANK,"12,98,771.00",-5.15,1.1,6.46,0,23.11,21,M,5,1,3,2,5,5
BHARTIARTL,"10,26,583.48",23.02,0.64,26.47,2.04,25.54,26,S,5,5,4,5,2,5
ICICIBANK,"8,82,070.18",7.85,1.27,18.21,0,18.26,26,S,4,5,3,4,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
VIPIND,"4,977.79",-21.61,1.17,-5.63,1.29,-0.88,10,HR,1,1,3,1,3,1
BALAMINES,"4,912.64",-29.34,2.03,30.37,0.01,10.24,18,R,1,1,1,5,5,5
RAJESHEXPO,"4,872.38",-50.67,0.5,-25.41,0.04,1.54,16,HR,1,1,5,1,5,3
SPARC,"4,687.39",-27.34,1.53,-2.99,0.49,-2.45,11,HR,1,1,2,1,5,1
EASEMYTRIP,"4,337.96",-13.88,1.5,-,0.03,0.08,17,R,1,1,3,5,5,2

In [38]:
data =pd.read_csv("/content/main.csv")
data

,Name,Market Cap,Alpha,Beta,5Y CAGR,D/E,EPS (Q),SCORE,Capability,b,c,d,e,f,g
0,RELIANCE,"16,45,671.87",-4.86,1,12.69,0.5,13.70,23,M,5,1,4,3,5,5
1,TCS,"14,14,726.49",-4.4,0.61,12.27,0.09,34.21,23,M,5,1,4,3,5,5
2,HDFCBANK,"12,98,771.00",-5.15,1.1,6.46,0,23.11,21,M,5,1,3,2,5,5
3,BHARTIARTL,"10,26,583.48",23.02,0.64,26.47,2.04,25.54,26,S,5,5,4,5,2,5
4,ICICIBANK,"8,82,070.18",7.85,1.27,18.21,0,18.26,26,S,4,5,3,4,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,VIPIND,"4,977.79",-21.61,1.17,-5.63,1.29,-0.88,10,HR,1,1,3,1,3,1
496,BALAMINES,"4,912.64",-29.34,2.03,30.37,0.01,10.24,18,R,1,1,1,5,5,5
497,RAJESHEXPO,"4,872.38",-50.67,0.5,-25.41,0.04,1.54,16,HR,1,1,5,1,5,3
498,SPARC,"4,687.39",-27.34,1.53,-2.99,0.49,-2.45,11,HR,1,1,2,1,5,1
499,EASEMYTRIP,"4,337.96",-13.88,1.5,-,0.03,0.08,17,R,1,1,3,5,5,2

In [39]:
data.Name.replace("TCS","TATA")

#Replace Attribute with another

0        RELIANCE
1            TATA
2        HDFCBANK
3      BHARTIARTL
4       ICICIBANK
          ...
495        VIPIND
496     BALAMINES
497    RAJESHEXPO
498         SPARC
499    EASEMYTRIP
Name: Name, Length: 500, dtype: object

In [47]:
pd.read_csv("/content/main.csv")

,Name,Market Cap,Alpha,Beta,5Y CAGR,D/E,EPS (Q),SCORE,Capability,b,c,d,e,f,g
0,RELIANCE,"16,45,671.87",-4.86,1,12.69,0.5,13.70,23,M,5,1,4,3,5,5
1,TCS,"14,14,726.49",-4.4,0.61,12.27,0.09,34.21,23,M,5,1,4,3,5,5
2,HDFCBANK,"12,98,771.00",-5.15,1.1,6.46,0,23.11,21,M,5,1,3,2,5,5
3,BHARTIARTL,"10,26,583.48",23.02,0.64,26.47,2.04,25.54,26,S,5,5,4,5,2,5
4,ICICIBANK,"8,82,070.18",7.85,1.27,18.21,0,18.26,26,S,4,5,3,4,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,VIPIND,"4,977.79",-21.61,1.17,-5.63,1.29,-0.88,10,HR,1,1,3,1,3,1
496,BALAMINES,"4,912.64",-29.34,2.03,30.37,0.01,10.24,18,R,1,1,1,5,5,5
497,RAJESHEXPO,"4,872.38",-50.67,0.5,-25.41,0.04,1.54,16,HR,1,1,5,1,5,3
498,SPARC,"4,687.39",-27.34,1.53,-2.99,0.49,-2.45,11,HR,1,1,2,1,5,1
499,EASEMYTRIP,"4,337.96",-13.88,1.5,-,0.03,0.08,17,R,1,1,3,5,5,2

In [48]:
data.rename(columns={"Name":"Company"})

#Replaces the Name with the company

,Company,Market Cap,Alpha,Beta,5Y CAGR,D/E,EPS (Q),SCORE,Capability,b,c,d,e,f,g,Rank
0,RELIANCE1,"16,45,671.87",-4.86,1,12.69,0.5,13.70,23,M,5,1,4,3,5,5,1
1,TCS2,"14,14,726.49",-4.4,0.61,12.27,0.09,34.21,23,M,5,1,4,3,5,5,2
2,HDFCBANK3,"12,98,771.00",-5.15,1.1,6.46,0,23.11,21,M,5,1,3,2,5,5,3
3,BHARTIARTL4,"10,26,583.48",23.02,0.64,26.47,2.04,25.54,26,S,5,5,4,5,2,5,4
4,ICICIBANK5,"8,82,070.18",7.85,1.27,18.21,0,18.26,26,S,4,5,3,4,5,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,VIPIND496,"4,977.79",-21.61,1.17,-5.63,1.29,-0.88,10,HR,1,1,3,1,3,1,496
496,BALAMINES497,"4,912.64",-29.34,2.03,30.37,0.01,10.24,18,R,1,1,1,5,5,5,497
497,RAJESHEXPO498,"4,872.38",-50.67,0.5,-25.41,0.04,1.54,16,HR,1,1,5,1,5,3,498
498,SPARC499,"4,687.39",-27.34,1.53,-2.99,0.49,-2.45,11,HR,1,1,2,1,5,1,499
499,EASEMYTRIP500,"4,337.96",-13.88,1.5,-,0.03,0.08,17,R,1,1,3,5,5,2,500

In [51]:
csv1 = pd.read_csv("/content/main.csv")
csv2 = pd.read_csv("/content/mnist_test.csv")

data = pd.concat([csv1,csv2])
data

,Name,Market Cap,Alpha,Beta,5Y CAGR,D/E,EPS (Q),SCORE,Capability,b,...,0.658,0.659,0.660,0.661,0.662,0.663,0.664,0.665,0.666,0.667
0,RELIANCE,"16,45,671.87",-4.86,1,12.69,0.5,13.70,23.0,M,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,TCS,"14,14,726.49",-4.4,0.61,12.27,0.09,34.21,23.0,M,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,HDFCBANK,"12,98,771.00",-5.15,1.1,6.46,0,23.11,21.0,M,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BHARTIARTL,"10,26,583.48",23.02,0.64,26.47,2.04,25.54,26.0,S,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ICICIBANK,"8,82,070.18",7.85,1.27,18.21,0,18.26,26.0,S,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Warning: Total number of columns (800) exceeds max_columns (20) limiting to first (20) columns.